default: &default
  host: "localhost"
  port: 3000

development:
  <<: *default

test:
  <<: *default

production: &production
  <<: *default
  # FIXME: change to the actual app's hostname
  host: "cfp.tropicalonrails.com"
  port: 443
